(function () {
  var FOOTER_HTML = [
    '<!-- Desktop footer -->',
    '<footer class="footer">',
    '  <div class="container">',
    '  <div class="footer-top">',
    '    <a class="footer-logo" href="index.html">',
    '      <img src="assets/footer-marco-logo-en.svg" alt="Marco" />',
    '    </a>',
    '    <div class="footer-social">',
    '      <div class="footer-social-icon">',
    '        <a href="https://www.linkedin.com/company/marcopayroll/" target="_blank" rel="noopener noreferrer">',
    '          <img src="assets/linkedin-icon.svg" alt="LinkedIn" />',
    '        </a>',
    '      </div>',
    '      <div class="footer-social-icon" style="cursor:pointer;" id="footer-wechat-btn">',
    '        <img src="assets/wechat-icon.svg" alt="WeChat" />',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div class="footer-nav">',
    '    <div class="footer-col">',
    '      <span class="footer-col-header" data-i18n="footer.col.services">Services</span>',
    '      <div class="footer-col-links">',
    '        <a href="service-global-payroll.html" data-i18n="link.payroll">Global Payroll</a>',
    '        <a href="service-employer-of-record.html" data-i18n="link.eor">EOR</a>',
    '        <a href="service-independent-contractor.html" data-i18n="link.ic">IC</a>',
    '        <a href="service-global-mobility.html" data-i18n="link.mobility">Global Mobility</a>',
    '        <a href="service-expense-processing.html" data-i18n="link.expense">Expense Processing</a>',
    '        <a href="service-hr-operations.html" data-i18n="link.hro">HRO</a>',
    '        <a href="service-service-delivery-model.html" data-i18n="link.sdm">Service Delivery Model</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-col">',
    '      <span class="footer-col-header" data-i18n="footer.col.compliance">Compliance</span>',
    '      <div class="footer-col-links">',
    '        <a href="compliance-data-protection.html" data-i18n="link.data">Data Protection &amp; Privacy</a>',
    '        <a href="compliance-operational-governance.html" data-i18n="link.opsgov">Operational Governance</a>',
    '        <a href="compliance-licensing-regulatory.html" data-i18n="link.licensing">Licensing &amp; Regulatory Compliance</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-col">',
    '      <span class="footer-col-header" data-i18n="footer.col.resources">Resources</span>',
    '      <div class="footer-col-links">',
    '        <a href="marco-os.html" data-i18n="link.marcosos">Marco OS</a>',
    '        <a href="https://help.marcopayroll.com/" target="_blank" rel="noopener noreferrer" data-i18n="link.help">Help Center</a>',
    '        <a href="https://developer.marcopayroll.com/" target="_blank" rel="noopener noreferrer" data-i18n="link.dev">Developer Portal</a>',
    '        <a href="https://test.tryglobalworkforce.com/" target="_blank" rel="noopener noreferrer" data-i18n="link.demo">Demo Site</a>',
    '        <a href="https://engine.marcopayroll.com/" target="_blank" rel="noopener noreferrer" data-i18n="link.engine">Processing &amp; Integration Engines</a>',
    '        <a href="#" data-i18n="link.copilot">Marco Copilot (AI Assistant)</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-col">',
    '      <span class="footer-col-header" data-i18n="footer.col.hub">HR Knowledge Hub</span>',
    '      <div class="footer-col-links">',
    '        <a href="hr-knowledge-hub-labor-cost-calculator.html" data-i18n="link.calculator">Labor Cost Calculator</a>',
    '        <a href="hr-knowledge-hub-country-guide.html" data-i18n="link.country">Country Guide</a>',
    '        <a href="hr-knowledge-hub-visa-guide.html" data-i18n="link.visa">Visa Guide</a>',
    '        <a href="hr-knowledge-hub-payroll-guide.html" data-i18n="link.payrollguide">Payroll Guide</a>',
    '        <a href="hr-knowledge-hub-freelancer-guide.html" data-i18n="link.freelancer">Freelancer Guide</a>',
    '        <a href="hr-knowledge-hub-employment-contract-matrix.html" data-i18n="link.contract">Employment Contract Matrix</a>',
    '        <a href="hr-knowledge-hub-work-schedule.html" data-i18n="link.schedule">Work Schedule</a>',
    '        <a href="hr-knowledge-hub-public-holiday-calendar-2026.html" data-i18n="link.holiday">Public Holiday Calendar</a>',
    '        <a href="hr-knowledge-hub-leave-policy.html" data-i18n="link.leave">Leave Policy</a>',
    '        <a href="hr-knowledge-hub-travel-expense-policy.html" data-i18n="link.travel">Travel &amp; Expense Policy</a>',
    '        <a href="hr-knowledge-hub-benefits-plan.html" data-i18n="link.benefits">Benefits Plan</a>',
    '        <a href="hr-knowledge-hub-government-claim-update.html" data-i18n="link.govtclaim">Government Claim Update</a>',
    '        <a href="hr-knowledge-hub-vendor-list.html" data-i18n="link.vendor">Vendor List</a>',
    '        <a href="hr-knowledge-hub-memo.html" data-i18n="link.memo">Memo</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-col">',
    '      <span class="footer-col-header" data-i18n="footer.col.price">Price</span>',
    '      <div class="footer-col-links">',
    '        <a href="price-global-workforce-solution.html" data-i18n="link.gws">Global Workforce Solution</a>',
    '        <a href="price-global-managed-payroll-service.html" data-i18n="link.gmps">Global Managed Payroll Service</a>',
    '        <a href="price-proposal-builder.html" data-i18n="link.proposal">Proposal Builder</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-col">',
    '      <span class="footer-col-header" data-i18n="footer.col.about">About</span>',
    '      <div class="footer-col-links">',
    '        <a href="company-vision-values.html" data-i18n="link.vision">Vision &amp; Value</a>',
    '        <a href="company-journey.html" data-i18n="link.journey">Marco\'s Journey</a>',
    '        <a href="company-entity-network.html" data-i18n="link.entity">Entity Network</a>',
    '        <a href="company-organization.html" data-i18n="link.org">Organization</a>',
    '        <a href="company-contact-us.html" data-i18n="link.contact">Contact Us</a>',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div class="footer-divider"></div>',
    '  <div class="footer-bottom">',
    '    <p data-i18n="footer.copyright">Copyright &copy; 2026 Marco Global Payroll Pte. Ltd. All rights reserved.</p>',
    '    <div class="footer-legal">',
    '      <a href="company-terms-of-use.html" data-i18n="link.terms">Terms of Use</a>',
    '      <a href="company-privacy-policy.html" data-i18n="link.privacy">Privacy Policy</a>',
    '      <a href="company-cookies-policy.html" data-i18n="link.cookies">Cookies Policy</a>',
    '    </div>',
    '  </div>',
    '  </div>',
    '</footer>',

    '<!-- Mobile footer -->',
    '<footer class="footer-mobile">',
    '  <div class="footer-mob-top">',
    '    <a class="footer-mob-logo" href="index.html">',
    '      <img src="assets/footer-marco-logo-en.svg" alt="Marco" />',
    '    </a>',
    '    <div class="footer-mob-social">',
    '      <a class="footer-mob-social-link" href="https://www.linkedin.com/company/marcopayroll/" target="_blank" rel="noopener noreferrer">',
    '        <img src="assets/linkedin-icon.svg" alt="LinkedIn" />',
    '      </a>',
    '      <div class="footer-mob-social-wechat" id="footer-mob-wechat-btn">',
    '        <img src="assets/wechat-icon.svg" alt="WeChat" />',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div class="footer-mob-acc">',
    '    <div class="footer-mob-row">',
    '      <div class="footer-mob-row-header" data-footer-mob-acc>',
    '        <span class="footer-mob-row-label" data-i18n="footer.col.services">Services</span>',
    '        <span class="footer-mob-row-chevron"><svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 6l4 4 4-4" stroke="#8f98b5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>',
    '      </div>',
    '      <div class="footer-mob-row-body">',
    '        <a href="service-global-payroll.html" data-i18n="link.payroll">Global Payroll</a>',
    '        <a href="service-employer-of-record.html" data-i18n="link.eor">EOR</a>',
    '        <a href="service-independent-contractor.html" data-i18n="link.ic">IC</a>',
    '        <a href="service-global-mobility.html" data-i18n="link.mobility">Global Mobility</a>',
    '        <a href="service-expense-processing.html" data-i18n="link.expense">Expense Processing</a>',
    '        <a href="service-hr-operations.html" data-i18n="link.hro">HRO</a>',
    '        <a href="service-service-delivery-model.html" data-i18n="link.sdm">Service Delivery Model</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-mob-row">',
    '      <div class="footer-mob-row-header" data-footer-mob-acc>',
    '        <span class="footer-mob-row-label" data-i18n="footer.col.compliance">Compliance</span>',
    '        <span class="footer-mob-row-chevron"><svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 6l4 4 4-4" stroke="#8f98b5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>',
    '      </div>',
    '      <div class="footer-mob-row-body">',
    '        <a href="compliance-data-protection.html" data-i18n="link.data">Data Protection &amp; Privacy</a>',
    '        <a href="compliance-operational-governance.html" data-i18n="link.opsgov">Operational Governance</a>',
    '        <a href="compliance-licensing-regulatory.html" data-i18n="link.licensing">Licensing &amp; Regulatory Compliance</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-mob-row">',
    '      <div class="footer-mob-row-header" data-footer-mob-acc>',
    '        <span class="footer-mob-row-label" data-i18n="footer.col.resources">Resources</span>',
    '        <span class="footer-mob-row-chevron"><svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 6l4 4 4-4" stroke="#8f98b5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>',
    '      </div>',
    '      <div class="footer-mob-row-body">',
    '        <a href="marco-os.html" data-i18n="link.marcosos">Marco OS</a>',
    '        <a href="https://help.marcopayroll.com/" target="_blank" rel="noopener noreferrer" data-i18n="link.help">Help Center</a>',
    '        <a href="https://developer.marcopayroll.com/" target="_blank" rel="noopener noreferrer" data-i18n="link.dev">Developer Portal</a>',
    '        <a href="https://test.tryglobalworkforce.com/" target="_blank" rel="noopener noreferrer" data-i18n="link.demo">Demo Site</a>',
    '        <a href="https://engine.marcopayroll.com/" target="_blank" rel="noopener noreferrer" data-i18n="link.engine">Processing &amp; Integration Engines</a>',
    '        <a href="#" data-i18n="link.copilot">Marco Copilot (AI Assistant)</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-mob-row">',
    '      <div class="footer-mob-row-header" data-footer-mob-acc>',
    '        <span class="footer-mob-row-label" data-i18n="footer.col.hub">HR Knowledge Hub</span>',
    '        <span class="footer-mob-row-chevron"><svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 6l4 4 4-4" stroke="#8f98b5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>',
    '      </div>',
    '      <div class="footer-mob-row-body">',
    '        <a href="hr-knowledge-hub-labor-cost-calculator.html" data-i18n="link.calculator">Labor Cost Calculator</a>',
    '        <a href="hr-knowledge-hub-country-guide.html" data-i18n="link.country">Country Guide</a>',
    '        <a href="hr-knowledge-hub-visa-guide.html" data-i18n="link.visa">Visa Guide</a>',
    '        <a href="hr-knowledge-hub-payroll-guide.html" data-i18n="link.payrollguide">Payroll Guide</a>',
    '        <a href="hr-knowledge-hub-freelancer-guide.html" data-i18n="link.freelancer">Freelancer Guide</a>',
    '        <a href="hr-knowledge-hub-employment-contract-matrix.html" data-i18n="link.contract">Employment Contract Matrix</a>',
    '        <a href="hr-knowledge-hub-work-schedule.html" data-i18n="link.schedule">Work Schedule</a>',
    '        <a href="hr-knowledge-hub-public-holiday-calendar-2026.html" data-i18n="link.holiday">Public Holiday Calendar</a>',
    '        <a href="hr-knowledge-hub-leave-policy.html" data-i18n="link.leave">Leave Policy</a>',
    '        <a href="hr-knowledge-hub-travel-expense-policy.html" data-i18n="link.travel">Travel &amp; Expense Policy</a>',
    '        <a href="hr-knowledge-hub-benefits-plan.html" data-i18n="link.benefits">Benefits Plan</a>',
    '        <a href="hr-knowledge-hub-government-claim-update.html" data-i18n="link.govtclaim">Government Claim Update</a>',
    '        <a href="hr-knowledge-hub-vendor-list.html" data-i18n="link.vendor">Vendor List</a>',
    '        <a href="hr-knowledge-hub-memo.html" data-i18n="link.memo">Memo</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-mob-row">',
    '      <div class="footer-mob-row-header" data-footer-mob-acc>',
    '        <span class="footer-mob-row-label" data-i18n="footer.col.price">Price</span>',
    '        <span class="footer-mob-row-chevron"><svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 6l4 4 4-4" stroke="#8f98b5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>',
    '      </div>',
    '      <div class="footer-mob-row-body">',
    '        <a href="price-global-workforce-solution.html" data-i18n="link.gws">Global Workforce Solution</a>',
    '        <a href="price-global-managed-payroll-service.html" data-i18n="link.gmps">Global Managed Payroll Service</a>',
    '        <a href="price-proposal-builder.html" data-i18n="link.proposal">Proposal Builder</a>',
    '      </div>',
    '    </div>',
    '    <div class="footer-mob-row">',
    '      <div class="footer-mob-row-header" data-footer-mob-acc>',
    '        <span class="footer-mob-row-label" data-i18n="footer.col.about">About</span>',
    '        <span class="footer-mob-row-chevron"><svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M4 6l4 4 4-4" stroke="#8f98b5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>',
    '      </div>',
    '      <div class="footer-mob-row-body">',
    '        <a href="company-vision-values.html" data-i18n="link.vision">Vision &amp; Value</a>',
    '        <a href="company-journey.html" data-i18n="link.journey">Marco\'s Journey</a>',
    '        <a href="company-entity-network.html" data-i18n="link.entity">Entity Network</a>',
    '        <a href="company-organization.html" data-i18n="link.org">Organization</a>',
    '        <a href="company-contact-us.html" data-i18n="link.contact">Contact Us</a>',
    '      </div>',
    '    </div>',
    '  </div>',
    '  <div class="footer-mob-legal">',
    '    <div class="footer-mob-legal-links">',
    '      <a href="company-terms-of-use.html" data-i18n="link.terms">Terms of Use</a>',
    '      <a href="company-privacy-policy.html" data-i18n="link.privacy">Privacy Policy</a>',
    '      <a href="company-cookies-policy.html" data-i18n="link.cookies">Cookies Policy</a>',
    '    </div>',
    '    <p class="footer-mob-copyright" data-i18n="footer.copyright">Copyright &copy; 2026 Marco Global Payroll Pte. Ltd. All rights reserved.</p>',
    '  </div>',
    '</footer>',

    '<div id="wechat-modal" class="wechat-modal">',
    '  <img src="assets/wechat-card.svg" alt="WeChat QR Code" />',
    '</div>'
  ].join('\n');

  document.body.insertAdjacentHTML('beforeend', FOOTER_HTML);

  /* Mobile footer accordion */
  document.querySelectorAll('[data-footer-mob-acc]').forEach(function (header) {
    header.addEventListener('click', function () {
      header.closest('.footer-mob-row').classList.toggle('is-open');
    });
  });

  /* WeChat modal — desktop & mobile open buttons */
  var modal = document.getElementById('wechat-modal');
  if (modal) {
    modal.addEventListener('click', function () {
      this.classList.remove('active');
    });
    var desktopBtn = document.getElementById('footer-wechat-btn');
    var mobileBtn  = document.getElementById('footer-mob-wechat-btn');
    if (desktopBtn) desktopBtn.addEventListener('click', function () { modal.classList.add('active'); });
    if (mobileBtn)  mobileBtn.addEventListener('click',  function () { modal.classList.add('active'); });
  }
})();
